version: "3.9"

services:

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data2: